import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { create } from 'zustand'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'devLinks: Online Link Sharing Generator',
  description: 'Generated by create next app',
  icons: {
    icon: '/img/favicon-32x32.png', // /public path
  },
}

const useStore = create((set) => ({
  bears: 0,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
}))

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={'h-full ' + inter.className}>{children}</body>
    </html>
  )
}
